import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@src/components/Navbar";
import { AuthProvider } from '@components/AuthContext';

const notoSans = Noto_Sans({
  variable: "--font-noto-sans"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/4073eb172d.js" crossOrigin="anonymous"></script>
      </head>
      <body
        className={`${notoSans.variable}`}
      >
        <section className="bg-gray-50 h-full">
          <Navbar />
          <AuthProvider>
          {children}
          </AuthProvider>
        </section>
      </body>
    </html>
  );
}
